
#개인 프로젝트용 ci/cd
#name: deploy to ec2
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  Deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: SSH로 ec2 접속
#        uses: appleboy/ssh-action@v1.0.3
#        env:
#          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ${{ secrets.EC2_USER }}
#          key: ${{ secrets.EC2_PRIVATE_KEY }}
#          envs: APPLICATION_PROPERTIES
#          script_stop: true
#          script: |
#            cd /home/ubuntu/git-study-CI-CD
#            rm -rf src/main/resources/application.properties
#            git pull origin main
#            mkdir -p src/main/resources
#            echo "$APPLICATION_PROPERTIES" > src/main/resources/application.properties
#            ./gradlew clean build
#            sudo fuser -k -n tcp 8080 || true
#            nohup java -jar ./build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &

# 팀 프로젝트용 ci/cd
name: deploy to ec2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: github repository 에 올린 파일들을 불러오기
        uses: actions/checkout@v4

      - name: JDK 17버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: resources 디렉토리 생성
        run: mkdir -p src/main/resources

      - name: application.properties 파일 가져오기
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application.properties

      - name: 테스트 및 빌드
        run: ./gradlew clean build

      - name: 빌드된 파일 이름 변경하기
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: SCP로 EC2에 빌드된 파일 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: project.jar
          target: /home/ubuntu/git-study-CI-CD/tobe
      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/git-study-CI-CD/current
            mkdir /home/ubuntu/git-study-CI-CD/current
            mv /home/ubuntu/git-study-CI-CD/tobe/project.jar /home/ubuntu/git-study-CI-CD/current/project.jar
            cd /home/ubuntu/git-study-CI-CD/current
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar project.jar > ./output.log 2>&1 &
            rm -rf /home/ubuntu/git-study-CI-CD/tobe